/*
 * AUTO-GENERATED BY CppBeSsot.
 * Direct edits are pointless: this file is regenerated.
 * Update the OpenAPI schema and/or CppBeSsot templates, then regenerate generated-* outputs.
 */
#include "cppbessot/model/Agent.h"

namespace models {
// Nlohmann-based models are header-only for now.
} // namespace models

