/* tslint:disable */
/* eslint-disable */
/**
 * cppbessot-test-schema-v1.2
 * Self-contained additive test fixture for cppbessot serdes and migration validation. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Agent
 */
export interface Agent {
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    role: string;
    /**
     * 
     * @type {boolean}
     * @memberof Agent
     */
    persistent: boolean;
    /**
     * 
     * @type {string}
     * @memberof Agent
     */
    displayName?: string;
    /**
     * 
     * @type {number}
     * @memberof Agent
     */
    trustScore?: number;
}

/**
 * Check if a given object implements the Agent interface.
 */
export function instanceOfAgent(value: object): value is Agent {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('persistent' in value) || value['persistent'] === undefined) return false;
    return true;
}

export function AgentFromJSON(json: any): Agent {
    return AgentFromJSONTyped(json, false);
}

export function AgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Agent {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'role': json['role'],
        'persistent': json['persistent'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'trustScore': json['trustScore'] == null ? undefined : json['trustScore'],
    };
}

export function AgentToJSON(json: any): Agent {
    return AgentToJSONTyped(json, false);
}

export function AgentToJSONTyped(value?: Agent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'role': value['role'],
        'persistent': value['persistent'],
        'displayName': value['displayName'],
        'trustScore': value['trustScore'],
    };
}

