/* tslint:disable */
/* eslint-disable */
/**
 * cppbessot-test-schema-v1.2
 * Self-contained additive test fixture for cppbessot serdes and migration validation. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GovernmentAddress
 */
export interface GovernmentAddress {
    /**
     * 
     * @type {string}
     * @memberof GovernmentAddress
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GovernmentAddress
     */
    addressLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof GovernmentAddress
     */
    regionLookupKey?: string;
}

/**
 * Check if a given object implements the GovernmentAddress interface.
 */
export function instanceOfGovernmentAddress(value: object): value is GovernmentAddress {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function GovernmentAddressFromJSON(json: any): GovernmentAddress {
    return GovernmentAddressFromJSONTyped(json, false);
}

export function GovernmentAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): GovernmentAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'addressLabel': json['addressLabel'] == null ? undefined : json['addressLabel'],
        'regionLookupKey': json['regionLookupKey'] == null ? undefined : json['regionLookupKey'],
    };
}

export function GovernmentAddressToJSON(json: any): GovernmentAddress {
    return GovernmentAddressToJSONTyped(json, false);
}

export function GovernmentAddressToJSONTyped(value?: GovernmentAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'addressLabel': value['addressLabel'],
        'regionLookupKey': value['regionLookupKey'],
    };
}

