/* tslint:disable */
/* eslint-disable */
/**
 * cppbessot-test-schema-v1.2
 * Self-contained additive test fixture for cppbessot serdes and migration validation. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TripAttemptResult
 */
export interface TripAttemptResult {
    /**
     * 
     * @type {string}
     * @memberof TripAttemptResult
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TripAttemptResult
     */
    result: string;
    /**
     * 
     * @type {string}
     * @memberof TripAttemptResult
     */
    retryReason?: string;
    /**
     * 
     * @type {string}
     * @memberof TripAttemptResult
     */
    governmentSuspensionReason?: string;
    /**
     * 
     * @type {string}
     * @memberof TripAttemptResult
     */
    governmentTerminationReason?: string;
    /**
     * 
     * @type {string}
     * @memberof TripAttemptResult
     */
    complianceSuspensionReason?: string;
    /**
     * 
     * @type {string}
     * @memberof TripAttemptResult
     */
    complianceTerminationReason?: string;
    /**
     * 
     * @type {string}
     * @memberof TripAttemptResult
     */
    policySuspensionReason?: string;
    /**
     * 
     * @type {string}
     * @memberof TripAttemptResult
     */
    policyTerminationReason?: string;
    /**
     * 
     * @type {string}
     * @memberof TripAttemptResult
     */
    cancelationReason?: string;
    /**
     * 
     * @type {string}
     * @memberof TripAttemptResult
     */
    failureReason?: string;
    /**
     * 
     * @type {string}
     * @memberof TripAttemptResult
     */
    details?: string;
}

/**
 * Check if a given object implements the TripAttemptResult interface.
 */
export function instanceOfTripAttemptResult(value: object): value is TripAttemptResult {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function TripAttemptResultFromJSON(json: any): TripAttemptResult {
    return TripAttemptResultFromJSONTyped(json, false);
}

export function TripAttemptResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TripAttemptResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'result': json['result'],
        'retryReason': json['retryReason'] == null ? undefined : json['retryReason'],
        'governmentSuspensionReason': json['governmentSuspensionReason'] == null ? undefined : json['governmentSuspensionReason'],
        'governmentTerminationReason': json['governmentTerminationReason'] == null ? undefined : json['governmentTerminationReason'],
        'complianceSuspensionReason': json['complianceSuspensionReason'] == null ? undefined : json['complianceSuspensionReason'],
        'complianceTerminationReason': json['complianceTerminationReason'] == null ? undefined : json['complianceTerminationReason'],
        'policySuspensionReason': json['policySuspensionReason'] == null ? undefined : json['policySuspensionReason'],
        'policyTerminationReason': json['policyTerminationReason'] == null ? undefined : json['policyTerminationReason'],
        'cancelationReason': json['cancelationReason'] == null ? undefined : json['cancelationReason'],
        'failureReason': json['failureReason'] == null ? undefined : json['failureReason'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function TripAttemptResultToJSON(json: any): TripAttemptResult {
    return TripAttemptResultToJSONTyped(json, false);
}

export function TripAttemptResultToJSONTyped(value?: TripAttemptResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'result': value['result'],
        'retryReason': value['retryReason'],
        'governmentSuspensionReason': value['governmentSuspensionReason'],
        'governmentTerminationReason': value['governmentTerminationReason'],
        'complianceSuspensionReason': value['complianceSuspensionReason'],
        'complianceTerminationReason': value['complianceTerminationReason'],
        'policySuspensionReason': value['policySuspensionReason'],
        'policyTerminationReason': value['policyTerminationReason'],
        'cancelationReason': value['cancelationReason'],
        'failureReason': value['failureReason'],
        'details': value['details'],
    };
}

