/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "GovernmentAddress";

CREATE TABLE IF NOT EXISTS "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" INTEGER NOT NULL,
  "migration" INTEGER NOT NULL);

DELETE FROM "schema_version"
  WHERE "name" = '';

CREATE TABLE "GovernmentAddress" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "addressLabel" TEXT NOT NULL,
  "regionLookupKey" TEXT NOT NULL);

INSERT OR IGNORE INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, 0);

