/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "TripAttemptResult";

CREATE TABLE IF NOT EXISTS "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" INTEGER NOT NULL,
  "migration" INTEGER NOT NULL);

DELETE FROM "schema_version"
  WHERE "name" = '';

CREATE TABLE "TripAttemptResult" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "result" TEXT NOT NULL,
  "retryReason" TEXT NOT NULL,
  "governmentSuspensionReason" TEXT NOT NULL,
  "governmentTerminationReason" TEXT NOT NULL,
  "complianceSuspensionReason" TEXT NOT NULL,
  "complianceTerminationReason" TEXT NOT NULL,
  "policySuspensionReason" TEXT NOT NULL,
  "policyTerminationReason" TEXT NOT NULL,
  "cancelationReason" TEXT NOT NULL,
  "failureReason" TEXT NOT NULL,
  "details" TEXT NOT NULL);

INSERT OR IGNORE INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, 0);

