/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE "Agent" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "role" TEXT NOT NULL,
  "persistent" BOOLEAN NOT NULL,
  "displayName" TEXT NOT NULL,
  "trustScore" INTEGER NOT NULL);

UPDATE "schema_version"
  SET "version" = 2, "migration" = TRUE
  WHERE "name" = '';

