/*
 * AUTO-GENERATED BY CppBeSsot.
 * Direct edits are pointless: this file is regenerated.
 * Update the OpenAPI schema and/or CppBeSsot templates, then regenerate generated-* outputs.
 */
#pragma once

#include <cstdint>
#include <string>

#include <nlohmann/json.hpp>
#include <odb/core.hxx>

namespace models {

#pragma db model version(1, 2)
#pragma db object table("GovernmentAddress")
class GovernmentAddress
{
public:
  #pragma db id
  // odbAddedIn: 1.1
  std::string id{};
  // odbAddedIn: 1.1
  std::string addressLabel{};
  // odbAddedIn: 1.1
  std::string regionLookupKey{};

  NLOHMANN_DEFINE_TYPE_INTRUSIVE(GovernmentAddress, id, addressLabel, regionLookupKey)

  nlohmann::json toJson() const
  {
    return nlohmann::json(*this);
  }

  static GovernmentAddress fromJson(const nlohmann::json& j)
  {
    return j.get<GovernmentAddress>();
  }
};

} // namespace models

