/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "Agent";

CREATE TABLE IF NOT EXISTS "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" INTEGER NOT NULL,
  "migration" INTEGER NOT NULL);

DELETE FROM "schema_version"
  WHERE "name" = '';

CREATE TABLE "Agent" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "role" TEXT NOT NULL,
  "persistent" INTEGER NOT NULL,
  "displayName" TEXT NOT NULL,
  "trustScore" INTEGER NOT NULL);

INSERT OR IGNORE INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 2, 0);

