/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE "GovernmentAddress" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "addressLabel" TEXT NOT NULL,
  "regionLookupKey" TEXT NOT NULL);

UPDATE "schema_version"
  SET "version" = 2, "migration" = 1
  WHERE "name" = '';

