/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE "TripAttemptResult" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "result" TEXT NOT NULL,
  "retryReason" TEXT NOT NULL,
  "governmentSuspensionReason" TEXT NOT NULL,
  "governmentTerminationReason" TEXT NOT NULL,
  "complianceSuspensionReason" TEXT NOT NULL,
  "complianceTerminationReason" TEXT NOT NULL,
  "policySuspensionReason" TEXT NOT NULL,
  "policyTerminationReason" TEXT NOT NULL,
  "cancelationReason" TEXT NOT NULL,
  "failureReason" TEXT NOT NULL,
  "details" TEXT NOT NULL);

UPDATE "schema_version"
  SET "version" = 2, "migration" = 1
  WHERE "name" = '';

