/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "GovernmentAddress" CASCADE;

DROP TABLE IF EXISTS "schema_version";

CREATE TABLE "GovernmentAddress" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "addressLabel" TEXT NOT NULL,
  "regionLookupKey" TEXT NOT NULL);

CREATE TABLE "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" BIGINT NOT NULL,
  "migration" BOOLEAN NOT NULL);

INSERT INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, FALSE);

