// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef TRIP_ATTEMPT_RESULT_ODB_HXX
#define TRIP_ATTEMPT_RESULT_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "TripAttemptResult.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // TripAttemptResult
  //
  template <>
  struct class_traits< ::models::TripAttemptResult >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::models::TripAttemptResult >
  {
    public:
    typedef ::models::TripAttemptResult object_type;
    typedef ::models::TripAttemptResult* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::std::string id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // TripAttemptResult
  //
  template <typename A>
  struct query_columns< ::models::TripAttemptResult, id_sqlite, A >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    id_type_;

    static const id_type_ id;

    // result
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    result_type_;

    static const result_type_ result;

    // retryReason
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    retryReason_type_;

    static const retryReason_type_ retryReason;

    // governmentSuspensionReason
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    governmentSuspensionReason_type_;

    static const governmentSuspensionReason_type_ governmentSuspensionReason;

    // governmentTerminationReason
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    governmentTerminationReason_type_;

    static const governmentTerminationReason_type_ governmentTerminationReason;

    // complianceSuspensionReason
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    complianceSuspensionReason_type_;

    static const complianceSuspensionReason_type_ complianceSuspensionReason;

    // complianceTerminationReason
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    complianceTerminationReason_type_;

    static const complianceTerminationReason_type_ complianceTerminationReason;

    // policySuspensionReason
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    policySuspensionReason_type_;

    static const policySuspensionReason_type_ policySuspensionReason;

    // policyTerminationReason
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    policyTerminationReason_type_;

    static const policyTerminationReason_type_ policyTerminationReason;

    // cancelationReason
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    cancelationReason_type_;

    static const cancelationReason_type_ cancelationReason;

    // failureReason
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    failureReason_type_;

    static const failureReason_type_ failureReason;

    // details
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    details_type_;

    static const details_type_ details;
  };

  template <typename A>
  const typename query_columns< ::models::TripAttemptResult, id_sqlite, A >::id_type_
  query_columns< ::models::TripAttemptResult, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::models::TripAttemptResult, id_sqlite, A >::result_type_
  query_columns< ::models::TripAttemptResult, id_sqlite, A >::
  result (A::table_name, "\"result\"", 0);

  template <typename A>
  const typename query_columns< ::models::TripAttemptResult, id_sqlite, A >::retryReason_type_
  query_columns< ::models::TripAttemptResult, id_sqlite, A >::
  retryReason (A::table_name, "\"retryReason\"", 0);

  template <typename A>
  const typename query_columns< ::models::TripAttemptResult, id_sqlite, A >::governmentSuspensionReason_type_
  query_columns< ::models::TripAttemptResult, id_sqlite, A >::
  governmentSuspensionReason (A::table_name, "\"governmentSuspensionReason\"", 0);

  template <typename A>
  const typename query_columns< ::models::TripAttemptResult, id_sqlite, A >::governmentTerminationReason_type_
  query_columns< ::models::TripAttemptResult, id_sqlite, A >::
  governmentTerminationReason (A::table_name, "\"governmentTerminationReason\"", 0);

  template <typename A>
  const typename query_columns< ::models::TripAttemptResult, id_sqlite, A >::complianceSuspensionReason_type_
  query_columns< ::models::TripAttemptResult, id_sqlite, A >::
  complianceSuspensionReason (A::table_name, "\"complianceSuspensionReason\"", 0);

  template <typename A>
  const typename query_columns< ::models::TripAttemptResult, id_sqlite, A >::complianceTerminationReason_type_
  query_columns< ::models::TripAttemptResult, id_sqlite, A >::
  complianceTerminationReason (A::table_name, "\"complianceTerminationReason\"", 0);

  template <typename A>
  const typename query_columns< ::models::TripAttemptResult, id_sqlite, A >::policySuspensionReason_type_
  query_columns< ::models::TripAttemptResult, id_sqlite, A >::
  policySuspensionReason (A::table_name, "\"policySuspensionReason\"", 0);

  template <typename A>
  const typename query_columns< ::models::TripAttemptResult, id_sqlite, A >::policyTerminationReason_type_
  query_columns< ::models::TripAttemptResult, id_sqlite, A >::
  policyTerminationReason (A::table_name, "\"policyTerminationReason\"", 0);

  template <typename A>
  const typename query_columns< ::models::TripAttemptResult, id_sqlite, A >::cancelationReason_type_
  query_columns< ::models::TripAttemptResult, id_sqlite, A >::
  cancelationReason (A::table_name, "\"cancelationReason\"", 0);

  template <typename A>
  const typename query_columns< ::models::TripAttemptResult, id_sqlite, A >::failureReason_type_
  query_columns< ::models::TripAttemptResult, id_sqlite, A >::
  failureReason (A::table_name, "\"failureReason\"", 0);

  template <typename A>
  const typename query_columns< ::models::TripAttemptResult, id_sqlite, A >::details_type_
  query_columns< ::models::TripAttemptResult, id_sqlite, A >::
  details (A::table_name, "\"details\"", 0);

  template <typename A>
  struct pointer_query_columns< ::models::TripAttemptResult, id_sqlite, A >:
    query_columns< ::models::TripAttemptResult, id_sqlite, A >
  {
  };

  template <>
  class access::object_traits_impl< ::models::TripAttemptResult, id_sqlite >:
    public access::object_traits< ::models::TripAttemptResult >
  {
    public:
    struct id_image_type
    {
      details::buffer id_value;
      std::size_t id_size;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      details::buffer id_value;
      std::size_t id_size;
      bool id_null;

      // result
      //
      details::buffer result_value;
      std::size_t result_size;
      bool result_null;

      // retryReason
      //
      details::buffer retryReason_value;
      std::size_t retryReason_size;
      bool retryReason_null;

      // governmentSuspensionReason
      //
      details::buffer governmentSuspensionReason_value;
      std::size_t governmentSuspensionReason_size;
      bool governmentSuspensionReason_null;

      // governmentTerminationReason
      //
      details::buffer governmentTerminationReason_value;
      std::size_t governmentTerminationReason_size;
      bool governmentTerminationReason_null;

      // complianceSuspensionReason
      //
      details::buffer complianceSuspensionReason_value;
      std::size_t complianceSuspensionReason_size;
      bool complianceSuspensionReason_null;

      // complianceTerminationReason
      //
      details::buffer complianceTerminationReason_value;
      std::size_t complianceTerminationReason_size;
      bool complianceTerminationReason_null;

      // policySuspensionReason
      //
      details::buffer policySuspensionReason_value;
      std::size_t policySuspensionReason_size;
      bool policySuspensionReason_null;

      // policyTerminationReason
      //
      details::buffer policyTerminationReason_value;
      std::size_t policyTerminationReason_size;
      bool policyTerminationReason_null;

      // cancelationReason
      //
      details::buffer cancelationReason_value;
      std::size_t cancelationReason_size;
      bool cancelationReason_null;

      // failureReason
      //
      details::buffer failureReason_value;
      std::size_t failureReason_size;
      bool failureReason_null;

      // details
      //
      details::buffer details_value;
      std::size_t details_size;
      bool details_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 12UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::models::TripAttemptResult, id_common >:
    public access::object_traits_impl< ::models::TripAttemptResult, id_sqlite >
  {
  };

  // TripAttemptResult
  //
}

#include "TripAttemptResult-odb.ixx"

#include <odb/post.hxx>

#endif // TRIP_ATTEMPT_RESULT_ODB_HXX
