/*
 * AUTO-GENERATED BY CppBeSsot.
 * Direct edits are pointless: this file is regenerated.
 * Update the OpenAPI schema and/or CppBeSsot templates, then regenerate generated-* outputs.
 */
#pragma once

#include <cstdint>
#include <string>

#include <nlohmann/json.hpp>
#include <odb/core.hxx>

namespace models {

#pragma db model version(1, 1)
#pragma db object table("TripAttemptResult")
class TripAttemptResult
{
public:
  #pragma db id
  // odbAddedIn: 1.1
  std::string id{};
  // odbAddedIn: 1.1
  std::string result{};
  // odbAddedIn: 1.1
  std::string retryReason{};
  // odbAddedIn: 1.1
  std::string governmentSuspensionReason{};
  // odbAddedIn: 1.1
  std::string governmentTerminationReason{};
  // odbAddedIn: 1.1
  std::string complianceSuspensionReason{};
  // odbAddedIn: 1.1
  std::string complianceTerminationReason{};
  // odbAddedIn: 1.1
  std::string policySuspensionReason{};
  // odbAddedIn: 1.1
  std::string policyTerminationReason{};
  // odbAddedIn: 1.1
  std::string cancelationReason{};
  // odbAddedIn: 1.1
  std::string failureReason{};
  // odbAddedIn: 1.1
  std::string details{};

  NLOHMANN_DEFINE_TYPE_INTRUSIVE(TripAttemptResult, id, result, retryReason, governmentSuspensionReason, governmentTerminationReason, complianceSuspensionReason, complianceTerminationReason, policySuspensionReason, policyTerminationReason, cancelationReason, failureReason, details)

  nlohmann::json toJson() const
  {
    return nlohmann::json(*this);
  }

  static TripAttemptResult fromJson(const nlohmann::json& j)
  {
    return j.get<TripAttemptResult>();
  }
};

} // namespace models

